import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const exportTransactionsPDF = (transactions = []) => {
  const doc = new jsPDF();

  // ====== Title ======
  doc.setFontSize(22);
  doc.setTextColor(37, 99, 235);
  doc.text("SpendWise", 14, 18);

  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text("Transaction Report", 14, 28);

  // ====== Date ======
  doc.setFontSize(10);
  doc.setTextColor(100);

  doc.text(`Generated on: ${new Date().toLocaleDateString("en-IN")}`, 14, 36);

  // ====== Totals ======

  const totalIncome = transactions
    .filter((t) => t.type === "income")
    .reduce((sum, t) => sum + Number(t.amount), 0);

  const totalExpense = transactions
    .filter((t) => t.type === "expense")
    .reduce((sum, t) => sum + Number(t.amount), 0);

  const balance = totalIncome - totalExpense;

  // ====== Table ======

  autoTable(doc, {
    startY: 45,

    head: [["Title", "Category", "Type", "Amount", "Date"]],

    body: transactions.map((transaction) => [
      transaction.title,
      transaction.category,
      transaction.type,
      `Rs. ${Number(transaction.amount).toLocaleString("en-IN")}`,
      new Date(transaction.date).toLocaleDateString("en-IN"),
    ]),

    styles: {
      fontSize: 10,
      cellPadding: 3,
    },

    headStyles: {
      fillColor: [37, 99, 235],
      textColor: [255, 255, 255],
    },

    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
  });

  // ====== Summary ======

  const finalY = doc.lastAutoTable.finalY + 15;

  doc.setFontSize(12);

  doc.text(
    `Total Income : Rs. ${totalIncome.toLocaleString("en-IN")}`,
    14,
    finalY,
  );

  doc.text(
    `Total Expense : Rs. ${totalExpense.toLocaleString("en-IN")}`,
    14,
    finalY + 8,
  );

  doc.text(
    `Net Balance : Rs. ${balance.toLocaleString("en-IN")}`,
    14,
    finalY + 18,
  );

  // ====== Footer ======

  doc.setFontSize(10);

  doc.setTextColor(120);

  doc.text("Generated by SpendWise", 14, doc.internal.pageSize.height - 10);

  // ====== Save ======

  doc.save(`transactions-${new Date().toISOString().split("T")[0]}.pdf`);
};
